import smtplib
from email.mime.text import MIMEText
from flask import render_template
import re
from email_validator import validate_email, EmailNotValidError

ALLOWED_EXTENSIONS = {'pdf'}
PASSWORD = "ftis dyfj qgom mzex"


    
def text(lang,fun):
    translations = {
    'arabic': [
        "الخطوات", 
        "قم بتحضير وتحديد الملفات على الجهاز المحمول الذي ستستخدمه في هذه العملية. فقط ملفات PDF وبحد أقصى لحجمها 10MB.",
        "قم بمسح رمز QR التالي وافتح الرابط الذي سيعيد توجيهك إلى بوابة تحميل الملفات.",
        "قم بتحميل الملفات من جهازك المحمول باتباع التعليمات المعروضة على البوابة.",
        "تحقق من أنك قد استلمت البريد الإلكتروني لتأكيد استلام الملفات بشكل صحيح وأدخل رمز الطلب الظاهر في البريد الإلكتروني في الحقل التالي. اضغط 'إرسال'.",
        "إذا نسيت تحميل ملف ما وترغب في إضافته إلى الطلب، كرر الخطوات من 2 إلى 4. اضغط 'إنهاء' عندما تكون مستعدًا.",
        "إرسال",
        "إنهاء",
        "عنوان البريد الإلكتروني",
        "أدخل بريدك الإلكتروني",
        "اختر ملفات PDF لتحميلها",
        "نحتاجها لإرسال بريد التأكيد مع رقم الطلب والمرجع حتى تتمكن من متابعة العملية.",
        "اضغط 'اختر الملفات' لاختيار الملفات المطلوبة.",
        "الحد الأقصى لحجم الملفات: 10MB",
        "استمرار",
        "أنت على وشك الانتهاء...",
        "تحقق من صندوق الوارد في بريدك الإلكتروني، لقد أرسلنا بريدًا لتأكيد الطلب مع رمز التعريف الذي ستحتاج إلى إدخاله في الحقل بالجهة المقابلة للاستمرار في إعداد الطباعة.",
        "إذا لم تتلقَ أي شيء، فمن المحتمل أن البريد الإلكتروني الذي أدخلته غير صحيح. في هذه الحالة، عد إلى الشاشة السابقة وأدخل البريد مرة أخرى. تحقق أيضًا من مجلد البريد غير الهام."
    ],
    'basque': [
        "Pausoak",
        "Prestatu eta kokatu fitxategiak erabiliko duzun mugikorrean. PDF fitxategiak soilik eta gehienez 10MB.",
        "Eskaneatu ondorengo QR kodea eta ireki esteka, zeinak fitxategiak igotzeko portalera bideratuko zaituen.",
        "Igo fitxategiak zure gailu mugikorretik, portalean agertzen diren jarraibideak jarraituz.",
        "Zure fitxategiak behar bezala jaso dituzula ziurtatu eta idatzi posta elektronikoan agertzen den eskaera identifikatzailea hurrengo eremuan. Sakatu 'Bidali'.",
        "Fitxategiren bat igotzea ahaztu bazaizu eta eskaerara gehitu nahi baduzu, errepikatu 2tik 4ra arteko urratsak. Sakatu 'Amaitu' dena prest duzunean.",
        "Bidali",
        "Amaitu",
        "E-posta helbidea",
        "Sartu zure posta elektronikoa",
        "Aukeratu igo beharreko PDF fitxategiak",
        "Behar dugu posta elektronikoaren baieztapena bidaltzeko, eskaeraren zenbakia eta erreferentzia jarraitzeko prozesuarekin.",
        "Sakatu 'Aukeratu fitxategiak' nahi dituzun fitxategiak aukeratzeko.",
        "Fitxategien gehienezko tamaina: 10MB",
        "Jarraitu",
        "Ia prest zaude...",
        "Egiaztatu zure posta elektronikoko sarrera-ontzia, eskaeraren identifikatzailea duen baieztapen-posta bidali dizugu. Idatzi identifikatzailea terminaleko laukian inprimaketa konfiguratzen jarraitzeko.",
        "Ez baduzu ezer jaso, baliteke sartutako posta elektronikoa ez izatea zuzena. Kasu horretan, itzuli aurreko pantailara eta sartu berriro posta. Egiaztatu ere zabor-postaren karpeta."
    ],
    'catalan': [
        "Passos",
        "Prepara i localitza els fitxers al dispositiu mòbil que usaràs en aquest procés. Només fitxers PDF i d'una mida màxima de 10MB.",
        "Escaneja el següent codi QR i obre l'enllaç que et redirigirà al portal de pujada de fitxers.",
        "Puja els fitxers des del teu dispositiu mòbil tot seguint les instruccions que es mostren al portal.",
        "Comprova que hagis rebut correctament el correu de confirmació de rebuda de fitxers i introdueix al següent espai l'identificador de comanda que es mostra al correu. Prem 'Enviar'.",
        "Si se t'ha oblidat pujar algun fitxer i el vols afegir a la comanda, repeteix els passos 2 a 4. Prem 'Acabar' quan ho tinguis tot llest.",
        "Enviar",
        "Acabar",
        "Adreça e-mail",
        "Introdueix el teu correu electrònic",
        "Selecciona els fitxers PDF a pujar",
        "La necessitem per a enviar-te el mail de confirmació amb el número de comanda i la referència per a què puguis seguir amb el procés",
        "Premeu 'Trieu els fitxers' per seleccionar els fitxers desitjats",
        "Mida màxima dels fitxers: 10MB",
        "Continuar",
        "Ja gairebé estàs...",
        "Comprova la safata d'entrada del teu correu electrònic, t'hem enviat un e-mail de confirmació de comanda amb l'identificador que hauràs d'introduir a la caixeta del terminal per procedir amb la configuració d'impressió.",
        "Si no has rebut res, és probable que l'adreça de correu que hagis introduït no sigui la correcta. En aquest cas, torna a l'anterior pantalla i introdueix de nou el correu. Comprova també la carpeta de correu brossa."
    ],
    'croatian': [
        "Koraci",
        "Pripremite i locirajte datoteke na mobilnom uređaju koji ćete koristiti u ovom procesu. Samo PDF datoteke maksimalne veličine 10MB.",
        "Skenirajte sljedeći QR kod i otvorite vezu koja će vas preusmjeriti na portal za prijenos datoteka.",
        "Prenesite datoteke sa svog mobilnog uređaja slijedeći upute prikazane na portalu.",
        "Provjerite jeste li ispravno primili e-poštu s potvrdom primitka datoteka i unesite identifikacijski broj narudžbe prikazan u e-pošti u sljedeće polje. Pritisnite 'Pošalji'.",
        "Ako ste zaboravili prenijeti neku datoteku i želite je dodati u narudžbu, ponovite korake od 2 do 4. Pritisnite 'Završi' kada ste spremni.",
        "Pošalji",
        "Završi",
        "Adresa e-pošte",
        "Unesite svoju e-mail adresu",
        "Odaberite PDF datoteke za prijenos",
        "Trebamo je za slanje e-pošte s potvrdom s brojem narudžbe i referencom kako biste mogli nastaviti s procesom.",
        "Pritisnite 'Odaberite datoteke' za odabir željenih datoteka.",
        "Maksimalna veličina datoteke: 10MB",
        "Nastavi",
        "Skoro ste gotovi...",
        "Provjerite ulaznu poštu vaše e-pošte, poslali smo vam e-poruku s potvrdom narudžbe s identifikacijskim brojem koji ćete morati unijeti u polje na terminalu kako biste nastavili s konfiguracijom ispisa.",
        "Ako ništa niste primili, moguće je da unesena adresa e-pošte nije točna. U tom slučaju, vratite se na prethodni zaslon i ponovno unesite adresu e-pošte. Također provjerite mapu za neželjenu poštu."
    ],
    'danish': [
        "Trin",
        "Forbered og lokaliser filerne på den mobile enhed, du vil bruge i denne proces. Kun PDF-filer og med en maksimal størrelse på 10MB.",
        "Scan den følgende QR-kode og åbn linket, som vil omdirigere dig til filoverførselsportalen.",
        "Upload filerne fra din mobile enhed ved at følge instruktionerne, der vises på portalen.",
        "Kontroller, at du har modtaget bekræftelses-e-mailen for filmodtagelsen korrekt, og indtast ordrenummeret, der vises i e-mailen, i det følgende felt. Tryk på 'Send'.",
        "Hvis du har glemt at uploade en fil og ønsker at tilføje den til ordren, skal du gentage trin 2 til 4. Tryk på 'Afslut', når du er klar.",
        "Send",
        "Afslut",
        "E-mail adresse",
        "Indtast din e-mail adresse",
        "Vælg de PDF-filer, der skal uploades",
        "Vi har brug for det for at sende dig en bekræftelsesmail med ordrenummeret og referencen, så du kan fortsætte med processen.",
        "Tryk på 'Vælg filer' for at vælge de ønskede filer.",
        "Maksimal filstørrelse: 10MB",
        "Fortsæt",
        "Du er næsten færdig...",
        "Kontroller din indbakke, vi har sendt dig en e-mail med bekræftelse af ordren og et identifikationsnummer, som du skal indtaste i feltet på terminalen for at fortsætte med printkonfigurationen.",
        "Hvis du ikke har modtaget noget, er det sandsynligt, at den e-mailadresse, du har indtastet, ikke er korrekt. I så fald skal du vende tilbage til den forrige skærm og indtaste e-mailen igen. Kontroller også din spam-mappe."
    ],
    'dutch': [
        "Stappen",
        "Bereid de bestanden voor en lokaliseer ze op het mobiele apparaat dat je in dit proces zult gebruiken. Alleen PDF-bestanden met een maximale grootte van 10MB.",
        "Scan de volgende QR-code en open de link die je naar het uploadportaal zal doorverwijzen.",
        "Upload de bestanden vanaf je mobiele apparaat door de instructies op het portaal te volgen.",
        "Controleer of je de bevestigingsmail van de ontvangst van bestanden correct hebt ontvangen en voer het bestelnummer in dat in de e-mail wordt weergegeven in het volgende veld. Druk op 'Verzenden'.",
        "Als je bent vergeten een bestand te uploaden en het aan de bestelling wilt toevoegen, herhaal dan de stappen 2 tot 4. Druk op 'Voltooien' wanneer je klaar bent.",
        "Verzenden",
        "Voltooien",
        "E-mailadres",
        "Voer je e-mailadres in",
        "Selecteer de te uploaden PDF-bestanden",
        "We hebben het nodig om je de bevestigingsmail te sturen met het bestelnummer en de referentie, zodat je verder kunt gaan met het proces.",
        "Druk op 'Bestanden selecteren' om de gewenste bestanden te kiezen.",
        "Maximale bestandsgrootte: 10MB",
        "Doorgaan",
        "Je bent bijna klaar...",
        "Controleer je inbox, we hebben je een bevestigingsmail van de bestelling gestuurd met een identificatienummer dat je in het veld op de terminal moet invoeren om verder te gaan met de printconfiguratie.",
        "Als je niets hebt ontvangen, is het waarschijnlijk dat het ingevoerde e-mailadres niet correct is. Ga in dat geval terug naar het vorige scherm en voer de e-mail opnieuw in. Controleer ook je spammap."
    ],
    'english': [
        "Steps",
        "Prepare and locate the files on the mobile device you will use in this process. Only PDF files and with a maximum size of 10MB.",
        "Scan the following QR code and open the link that will redirect you to the file upload portal.",
        "Upload the files from your mobile device following the instructions displayed on the portal.",
        "Check that you have correctly received the file receipt confirmation email and enter the order identifier shown in the email in the following field. Press 'Send'.",
        "If you forgot to upload a file and want to add it to the order, repeat steps 2 to 4. Press 'Finish' when you are ready.",
        "Send",
        "Finish",
        "Email address",
        "Enter your email address",
        "Select the PDF files to upload",
        "We need it to send you the confirmation email with the order number and reference so you can continue with the process.",
        "Press 'Choose files' to select the desired files.",
        "Maximum file size: 10MB",
        "Continue",
        "You're almost there...",
        "Check your email inbox, we've sent you an order confirmation email with the identifier that you'll need to enter in the terminal box to proceed with the print configuration.",
        "If you haven't received anything, it's likely that the email address you entered is incorrect. In this case, return to the previous screen and enter the email again. Also check the spam folder."
    ],
    'filipino': [
        "Mga Hakbang",
        "Ihanda at hanapin ang mga file sa mobile device na gagamitin mo sa prosesong ito. Mga PDF file lamang at may maximum na laki na 10MB.",
        "I-scan ang sumusunod na QR code at buksan ang link na ire-redirect ka sa file upload portal.",
        "I-upload ang mga file mula sa iyong mobile device sa pamamagitan ng pagsunod sa mga tagubilin na ipinapakita sa portal.",
        "Siguraduhin na tama mong natanggap ang email na kumpirmasyon ng pagtanggap ng file at ilagay ang order identifier na ipinapakita sa email sa sumusunod na field. Pindutin ang 'Ipadala'.",
        "Kung nakalimutan mong mag-upload ng isang file at nais mong idagdag ito sa order, ulitin ang mga hakbang 2 hanggang 4. Pindutin ang 'Tapusin' kapag handa ka na.",
        "Ipadala",
        "Tapusin",
        "Email address",
        "Ilagay ang iyong email address",
        "Piliin ang mga PDF file na ia-upload",
        "Kailangan namin ito upang maipadala sa iyo ang email na kumpirmasyon na may order number at reference upang magpatuloy ka sa proseso.",
        "Pindutin ang 'Piliin ang mga file' upang piliin ang mga nais na file.",
        "Maximum na laki ng file: 10MB",
        "Magpatuloy",
        "Halos tapos ka na...",
        "Suriin ang iyong email inbox, nagpadala kami sa iyo ng email ng kumpirmasyon ng order na may identifier na kakailanganin mong ilagay sa kahon ng terminal upang magpatuloy sa pag-configure ng pag-print.",
        "Kung wala kang natanggap, malamang na ang email address na iyong inilagay ay hindi tama. Sa kasong ito, bumalik sa nakaraang screen at ilagay muli ang email. Suriin din ang folder ng spam."
    ],
    'french': [
        "Étapes",
        "Préparez et localisez les fichiers sur l'appareil mobile que vous utiliserez dans ce processus. Uniquement des fichiers PDF et avec une taille maximale de 10 Mo.",
        "Scannez le code QR suivant et ouvrez le lien qui vous redirigera vers le portail de téléchargement de fichiers.",
        "Téléchargez les fichiers depuis votre appareil mobile en suivant les instructions affichées sur le portail.",
        "Vérifiez que vous avez bien reçu l'email de confirmation de réception des fichiers et saisissez l'identifiant de commande affiché dans l'email dans le champ suivant. Appuyez sur 'Envoyer'.",
        "Si vous avez oublié de télécharger un fichier et souhaitez l'ajouter à la commande, répétez les étapes 2 à 4. Appuyez sur 'Terminer' lorsque vous êtes prêt.",
        "Envoyer",
        "Terminer",
        "Adresse e-mail",
        "Entrez votre adresse e-mail",
        "Sélectionnez les fichiers PDF à télécharger",
        "Nous en avons besoin pour vous envoyer l'email de confirmation avec le numéro de commande et la référence pour que vous puissiez poursuivre le processus.",
        "Appuyez sur 'Choisir les fichiers' pour sélectionner les fichiers souhaités.",
        "Taille maximale des fichiers : 10 Mo",
        "Continuer",
        "Vous y êtes presque...",
        "Vérifiez votre boîte de réception, nous vous avons envoyé un email de confirmation de commande avec l'identifiant que vous devrez saisir dans la case du terminal pour poursuivre la configuration de l'impression.",
        "Si vous n'avez rien reçu, il est probable que l'adresse e-mail que vous avez saisie soit incorrecte. Dans ce cas, revenez à l'écran précédent et saisissez de nouveau l'e-mail. Vérifiez également le dossier de spam."
    ],
    'gd': [
        "Ceumannan",
        "Ullachadh agus lorg na faidhlichean air an inneal gluasadach a chleachdas tu sa phròiseas seo. A-mhàin faidhlichean PDF agus le meud as motha de 10MB.",
        "Sgan an còd QR a leanas agus fosgail an ceangal a thèid do thoirt chun a' phuirt airson faidhlichean a luchdadh suas.",
        "Luchdaich suas na faidhlichean bhon inneal gluasadach agad a 'leantainn nan stiùiridhean a tha air an sealltainn air a' phort.",
        "Thoir sùil air a bheil thu air a 'phost-dearbhaidh fhaighinn ceart agus cuir a-steach an t-inbhe òrdugh a tha air a shealltainn sa phost-dealain sa phàirt a leanas. Brùth air 'Cuir'.",
        "Ma dhìochuimhnich thu faidhle a luchdadh suas agus ma tha thu airson a chur ris an òrdugh, dèan a-rithist na ceumannan 2 gu 4. Brùth air 'Crìochnaich' nuair a bhios tu deiseil.",
        "Cuir",
        "Crìochnaich",
        "Seòladh post-d",
        "Cuir a-steach an seòladh post-d agad",
        "Tagh na faidhlichean PDF ri luchdachadh suas",
        "Feumaidh sinn e gus am post-d dearbhaidh a chur thugad le àireamh an òrduigh agus an t-iomradh gus an urrainn dhut leantainn air adhart leis a 'phròiseas.",
        "Brùth air 'Tagh faidhlichean' gus na faidhlichean a tha thu ag iarraidh a thaghadh.",
        "Meud as motha de na faidhlichean: 10MB",
        "Lean air adhart",
        "Tha thu faisg air a chrìochnachadh...",
        "Thoir sùil air a’ bhogsa a-steach post-d agad, tha sinn air post-d dearbhaidh òrdugh a chuir thugad le inbhe a dh’ fheumas tu a chuir a-steach sa bhogsa air a’ phort-uidheim gus leantainn air adhart le rèiteachadh clò-bhualaidh.",
        "Mura h-eil thu air dad fhaighinn, tha e coltach nach eil an seòladh post-d a chuir thu a-steach ceart. Anns a 'chùis seo, till air ais chun na sgrìn roimhe agus cuir a-steach am post-d a-rithist. Thoir sùil cuideachd air a' phasgan spama."
    ],
    'german': [
        "Schritte",
        "Bereiten Sie die Dateien vor und lokalisieren Sie sie auf dem mobilen Gerät, das Sie in diesem Prozess verwenden werden. Nur PDF-Dateien und mit einer maximalen Größe von 10MB.",
        "Scannen Sie den folgenden QR-Code und öffnen Sie den Link, der Sie zum Datei-Upload-Portal weiterleitet.",
        "Laden Sie die Dateien von Ihrem mobilen Gerät hoch, indem Sie den Anweisungen auf dem Portal folgen.",
        "Überprüfen Sie, ob Sie die Bestätigungs-E-Mail für den Dateieingang korrekt erhalten haben, und geben Sie die in der E-Mail angezeigte Bestellnummer in das folgende Feld ein. Drücken Sie 'Senden'.",
        "Wenn Sie eine Datei vergessen haben hochzuladen und diese zur Bestellung hinzufügen möchten, wiederholen Sie die Schritte 2 bis 4. Drücken Sie 'Beenden', wenn Sie bereit sind.",
        "Senden",
        "Beenden",
        "E-Mail-Adresse",
        "Geben Sie Ihre E-Mail-Adresse ein",
        "Wählen Sie die hochzuladenden PDF-Dateien aus",
        "Wir benötigen sie, um Ihnen die Bestätigungs-E-Mail mit der Bestellnummer und der Referenz zu senden, damit Sie mit dem Prozess fortfahren können.",
        "Drücken Sie 'Dateien auswählen', um die gewünschten Dateien auszuwählen.",
        "Maximale Dateigröße: 10MB",
        "Fortfahren",
        "Sie sind fast fertig...",
        "Überprüfen Sie Ihren E-Mail-Posteingang, wir haben Ihnen eine Bestätigungs-E-Mail mit der Bestellnummer gesendet, die Sie in das Terminalfeld eingeben müssen, um mit der Druckkonfiguration fortzufahren.",
        "Wenn Sie nichts erhalten haben, ist es wahrscheinlich, dass die eingegebene E-Mail-Adresse nicht korrekt ist. In diesem Fall kehren Sie zum vorherigen Bildschirm zurück und geben Sie die E-Mail erneut ein. Überprüfen Sie auch den Spam-Ordner."
    ],
    'greek': [
        "Βήματα",
        "Προετοιμάστε και εντοπίστε τα αρχεία στη φορητή συσκευή που θα χρησιμοποιήσετε σε αυτήν τη διαδικασία. Μόνο αρχεία PDF και με μέγιστο μέγεθος 10MB.",
        "Σαρώστε τον παρακάτω κωδικό QR και ανοίξτε τον σύνδεσμο που θα σας ανακατευθύνει στην πύλη μεταφόρτωσης αρχείων.",
        "Μεταφορτώστε τα αρχεία από τη φορητή συσκευή σας ακολουθώντας τις οδηγίες που εμφανίζονται στην πύλη.",
        "Ελέγξτε αν έχετε λάβει σωστά το email επιβεβαίωσης παραλαβής αρχείων και εισάγετε το αναγνωριστικό παραγγελίας που εμφανίζεται στο email στο επόμενο πεδίο. Πατήστε 'Αποστολή'.",
        "Αν ξεχάσατε να μεταφορτώσετε κάποιο αρχείο και θέλετε να το προσθέσετε στην παραγγελία, επαναλάβετε τα βήματα 2 έως 4. Πατήστε 'Τέλος' όταν είστε έτοιμοι.",
        "Αποστολή",
        "Τέλος",
        "Διεύθυνση ηλεκτρονικού ταχυδρομείου",
        "Εισαγάγετε τη διεύθυνση email σας",
        "Επιλέξτε τα αρχεία PDF που θα μεταφορτωθούν",
        "Το χρειαζόμαστε για να σας στείλουμε το email επιβεβαίωσης με τον αριθμό παραγγελίας και την αναφορά, ώστε να συνεχίσετε τη διαδικασία.",
        "Πατήστε 'Επιλέξτε αρχεία' για να επιλέξετε τα επιθυμητά αρχεία.",
        "Μέγιστο μέγεθος αρχείου: 10MB",
        "Συνέχεια",
        "Είστε σχεδόν έτοιμοι...",
        "Ελέγξτε τα εισερχόμενα email σας, σας στείλαμε ένα email επιβεβαίωσης παραγγελίας με το αναγνωριστικό που θα πρέπει να εισαγάγετε στο πλαίσιο του τερματικού για να προχωρήσετε με τη διαμόρφωση εκτύπωσης.",
        "Εάν δεν έχετε λάβει τίποτα, είναι πιθανό ότι η διεύθυνση email που εισαγάγατε δεν είναι σωστή. Σε αυτή την περίπτωση, επιστρέψτε στην προηγούμενη οθόνη και εισαγάγετε ξανά το email. Ελέγξτε επίσης τον φάκελο ανεπιθύμητης αλληλογραφίας."
    ],
    'italian': [
        "Passaggi",
        "Prepara e individua i file sul dispositivo mobile che utilizzerai in questo processo. Solo file PDF e con una dimensione massima di 10MB.",
        "Scansiona il seguente codice QR e apri il link che ti reindirizzerà al portale di caricamento dei file.",
        "Carica i file dal tuo dispositivo mobile seguendo le istruzioni visualizzate sul portale.",
        "Verifica di aver ricevuto correttamente l'email di conferma di ricezione dei file e inserisci l'identificativo dell'ordine mostrato nell'email nel campo seguente. Premi 'Invia'.",
        "Se hai dimenticato di caricare un file e desideri aggiungerlo all'ordine, ripeti i passaggi da 2 a 4. Premi 'Fine' quando sei pronto.",
        "Invia",
        "Fine",
        "Indirizzo email",
        "Inserisci il tuo indirizzo email",
        "Seleziona i file PDF da caricare",
        "Ne abbiamo bisogno per inviarti l'email di conferma con il numero dell'ordine e il riferimento per poter proseguire con il processo.",
        "Premi 'Scegli file' per selezionare i file desiderati.",
        "Dimensione massima del file: 10MB",
        "Continua",
        "Sei quasi arrivato...",
        "Controlla la tua casella di posta elettronica, ti abbiamo inviato un'email di conferma dell'ordine con l'identificativo che dovrai inserire nella casella del terminale per procedere con la configurazione di stampa.",
        "Se non hai ricevuto nulla, è probabile che l'indirizzo email che hai inserito non sia corretto. In tal caso, torna alla schermata precedente e inserisci di nuovo l'email. Controlla anche la cartella della posta indesiderata."
    ],
    'japanese': [
        "ステップ",
        "このプロセスで使用するモバイルデバイスにファイルを準備して配置します。PDFファイルのみで、最大サイズは10MBです。",
        "次のQRコードをスキャンし、ファイルアップロードポータルにリダイレクトされるリンクを開きます。",
        "ポータルに表示される指示に従って、モバイルデバイスからファイルをアップロードします。",
        "ファイル受信確認のメールを正しく受信したことを確認し、メールに表示されている注文識別子を次のフィールドに入力します。「送信」を押します。",
        "ファイルのアップロードを忘れてしまい、注文に追加したい場合は、ステップ2〜4を繰り返します。準備が整ったら「完了」を押します。",
        "送信",
        "完了",
        "メールアドレス",
        "メールアドレスを入力してください",
        "アップロードするPDFファイルを選択します",
        "注文番号と参照を含む確認メールを送信するために必要です。",
        "「ファイルを選択」を押して、目的のファイルを選択します。",
        "最大ファイルサイズ：10MB",
        "続行",
        "ほぼ完了です...",
        "メールボックスを確認してください。注文確認メールを識別子と共に送信しました。印刷設定を続行するために、端末のボックスに識別子を入力する必要があります。",
        "何も受信していない場合、入力したメールアドレスが正しくない可能性があります。その場合は、前の画面に戻ってメールを再入力してください。迷惑メールフォルダも確認してください。"
    ],
    'norwegian': [
        "Trinn",
        "Forbered og finn filene på mobilenheten du vil bruke i denne prosessen. Kun PDF-filer med en maksimal størrelse på 10MB.",
        "Skann følgende QR-kode og åpne lenken som vil omdirigere deg til filopplastingsportalen.",
        "Last opp filene fra mobilenheten din ved å følge instruksjonene som vises på portalen.",
        "Kontroller at du har mottatt bekreftelses-e-posten for filmottaket riktig og skriv inn bestillings-ID-en som vises i e-posten i det følgende feltet. Trykk på 'Send'.",
        "Hvis du glemte å laste opp en fil og vil legge den til i bestillingen, gjenta trinnene 2 til 4. Trykk på 'Fullfør' når du er klar.",
        "Send",
        "Fullfør",
        "E-postadresse",
        "Skriv inn e-postadressen din",
        "Velg PDF-filene du vil laste opp",
        "Vi trenger det for å sende deg bekreftelses-e-posten med bestillingsnummeret og referansen slik at du kan fortsette med prosessen.",
        "Trykk på 'Velg filer' for å velge ønskede filer.",
        "Maksimal filstørrelse: 10MB",
        "Fortsett",
        "Du er nesten ferdig...",
        "Sjekk innboksen din, vi har sendt deg en bekreftelses-e-post med bestillings-ID-en som du må skrive inn i feltet på terminalen for å fortsette med utskriftskonfigurasjonen.",
        "Hvis du ikke har mottatt noe, er det sannsynlig at e-postadressen du skrev inn, ikke er korrekt. I så fall gå tilbake til forrige skjermbilde og skriv inn e-posten på nytt. Sjekk også spam-mappen."
    ],
    'polish': [
        "Kroki",
        "Przygotuj i zlokalizuj pliki na urządzeniu mobilnym, którego użyjesz w tym procesie. Tylko pliki PDF o maksymalnym rozmiarze 10MB.",
        "Zeskanuj poniższy kod QR i otwórz link, który przekieruje cię do portalu przesyłania plików.",
        "Prześlij pliki ze swojego urządzenia mobilnego, postępując zgodnie z instrukcjami wyświetlanymi na portalu.",
        "Sprawdź, czy poprawnie otrzymałeś wiadomość e-mail z potwierdzeniem odbioru plików i wprowadź identyfikator zamówienia wyświetlany w wiadomości e-mail w następnym polu. Naciśnij 'Wyślij'.",
        "Jeśli zapomniałeś przesłać jakiś plik i chcesz go dodać do zamówienia, powtórz kroki 2 do 4. Naciśnij 'Zakończ', gdy będziesz gotowy.",
        "Wyślij",
        "Zakończ",
        "Adres e-mail",
        "Wprowadź swój adres e-mail",
        "Wybierz pliki PDF do przesłania",
        "Potrzebujemy go, aby wysłać ci e-mail z potwierdzeniem wraz z numerem zamówienia i referencją, abyś mógł kontynuować proces.",
        "Naciśnij 'Wybierz pliki', aby wybrać żądane pliki.",
        "Maksymalny rozmiar pliku: 10MB",
        "Kontynuuj",
        "Prawie gotowe...",
        "Sprawdź swoją skrzynkę odbiorczą, wysłaliśmy ci wiadomość e-mail z potwierdzeniem zamówienia i identyfikatorem, który musisz wprowadzić w polu na terminalu, aby kontynuować konfigurację drukowania.",
        "Jeśli nic nie otrzymałeś, prawdopodobnie wprowadziłeś nieprawidłowy adres e-mail. W takim przypadku wróć do poprzedniego ekranu i wprowadź ponownie e-mail. Sprawdź także folder spamu."
    ],
    'portuguese': [
        "Passos",
        "Prepare e localize os arquivos no dispositivo móvel que você usará neste processo. Apenas arquivos PDF com um tamanho máximo de 10MB.",
        "Digitalize o seguinte código QR e abra o link que redirecionará você para o portal de upload de arquivos.",
        "Carregue os arquivos do seu dispositivo móvel seguindo as instruções exibidas no portal.",
        "Verifique se você recebeu corretamente o e-mail de confirmação de recebimento dos arquivos e insira o identificador do pedido exibido no e-mail no campo a seguir. Pressione 'Enviar'.",
        "Se você esqueceu de carregar algum arquivo e deseja adicioná-lo ao pedido, repita os passos 2 a 4. Pressione 'Concluir' quando estiver pronto.",
        "Enviar",
        "Concluir",
        "Endereço de e-mail",
        "Digite seu endereço de e-mail",
        "Selecione os arquivos PDF para carregar",
        "Precisamos disso para enviar-lhe o e-mail de confirmação com o número do pedido e a referência para que você possa continuar com o processo.",
        "Pressione 'Escolher arquivos' para selecionar os arquivos desejados.",
        "Tamanho máximo do arquivo: 10MB",
        "Continuar",
        "Você está quase lá...",
        "Verifique sua caixa de entrada de e-mail, enviamos-lhe um e-mail de confirmação de pedido com o identificador que você precisará inserir na caixa do terminal para prosseguir com a configuração da impressão.",
        "Se você não recebeu nada, é provável que o endereço de e-mail que você inseriu esteja incorreto. Nesse caso, volte para a tela anterior e insira novamente o e-mail. Verifique também a pasta de spam."
    ],
    'serbian': [
        "Koraci",
        "Pripremite i locirajte datoteke na mobilnom uređaju koji ćete koristiti u ovom procesu. Samo PDF datoteke maksimalne veličine 10MB.",
        "Skenirajte sledeći QR kod i otvorite link koji će vas preusmeriti na portal za prijenos datoteka.",
        "Prenesite datoteke sa svog mobilnog uređaja prateći uputstva prikazana na portalu.",
        "Proverite da li ste ispravno primili e-poštu sa potvrdom prijema datoteka i unesite identifikacioni broj narudžbine prikazan u e-pošti u sledeće polje. Pritisnite 'Pošalji'.",
        "Ako ste zaboravili preneti neku datoteku i želite je dodati u narudžbinu, ponovite korake od 2 do 4. Pritisnite 'Završi' kada ste spremni.",
        "Pošalji",
        "Završi",
        "Adresa e-pošte",
        "Unesite svoju e-mail adresu",
        "Odaberite PDF datoteke za prijenos",
        "Potrebno nam je kako bismo vam poslali e-poštu sa potvrdom i brojem narudžbine i referencom kako biste mogli nastaviti sa procesom.",
        "Pritisnite 'Odaberite datoteke' za odabir željenih datoteka.",
        "Maksimalna veličina datoteke: 10MB",
        "Nastavi",
        "Skoro ste gotovi...",
        "Proverite ulaznu poštu vaše e-pošte, poslali smo vam e-poruku sa potvrdom narudžbine i identifikacionim brojem koji ćete morati uneti u polje na terminalu kako biste nastavili sa podešavanjem štampanja.",
        "Ako ništa niste primili, moguće je da unesena adresa e-pošte nije tačna. U tom slučaju, vratite se na prethodni ekran i ponovo unesite adresu e-pošte. Takođe proverite mapu za neželjenu poštu."
    ],
    'spanish': [
        "Pasos",
        "Prepara y localiza los archivos en el dispositivo móvil que usarás en este proceso. Solo archivos PDF y con un tamaño máximo de 10MB.",
        "Escanea el siguiente código QR y abre el enlace que te redirigirá al portal de subida de archivos.",
        "Sube los archivos desde tu dispositivo móvil siguiendo las instrucciones que se muestran en el portal.",
        "Comprueba que hayas recibido correctamente el correo de confirmación de recepción de archivos e introduce en el siguiente espacio el identificador de pedido que se muestra en el correo. Presiona 'Enviar'.",
        "Si se te ha olvidado subir algún archivo y lo quieres añadir al pedido, repite los pasos 2 a 4. Presiona 'Finalizar' cuando lo tengas todo listo.",
        "Enviar",
        "Finalizar",
        "Dirección de correo electrónico",
        "Introduce tu correo electrónico",
        "Selecciona los archivos PDF a subir",
        "Lo necesitamos para enviarte el correo de confirmación con el número de pedido y la referencia para que puedas continuar con el proceso.",
        "Presiona 'Seleccionar archivos' para elegir los archivos deseados.",
        "Tamaño máximo de los archivos: 10MB",
        "Continuar",
        "Ya casi estás...",
        "Revisa la bandeja de entrada de tu correo electrónico, te hemos enviado un correo de confirmación de pedido con el identificador que deberás introducir en la casilla del terminal para proceder con la configuración de impresión.",
        "Si no has recibido nada, es probable que la dirección de correo que hayas introducido no sea la correcta. En ese caso, vuelve a la pantalla anterior e introduce de nuevo el correo. Revisa también la carpeta de correo no deseado."
    ],
    'swedish': [
        "Steg",
        "Förbered och lokalisera filerna på den mobila enheten som du kommer att använda i denna process. Endast PDF-filer och med en maximal storlek på 10MB.",
        "Skanna följande QR-kod och öppna länken som omdirigerar dig till uppladdningsportalen för filer.",
        "Ladda upp filerna från din mobila enhet genom att följa instruktionerna som visas på portalen.",
        "Kontrollera att du har tagit emot e-postbekräftelsen för mottagandet av filer korrekt och ange beställnings-ID som visas i e-posten i följande fält. Tryck på 'Skicka'.",
        "Om du har glömt att ladda upp en fil och vill lägga till den i beställningen, upprepa steg 2 till 4. Tryck på 'Avsluta' när du är redo.",
        "Skicka",
        "Avsluta",
        "E-postadress",
        "Ange din e-postadress",
        "Välj de PDF-filer som ska laddas upp",
        "Vi behöver det för att skicka bekräftelsemejlet till dig med beställningsnummer och referens så att du kan fortsätta med processen.",
        "Tryck på 'Välj filer' för att välja de önskade filerna.",
        "Maximal filstorlek: 10MB",
        "Fortsätt",
        "Du är nästan klar...",
        "Kontrollera din e-postinkorg, vi har skickat ett bekräftelsemejl med beställnings-ID som du behöver ange i rutan på terminalen för att fortsätta med utskriftskonfigurationen.",
        "Om du inte har fått något, är det troligt att den e-postadress du angav inte är korrekt. I så fall gå tillbaka till föregående skärm och ange e-posten igen. Kontrollera också skräppostmappen."
    ],
    'turkish': [
        "Adımlar",
        "Bu işlemde kullanacağınız mobil cihazdaki dosyaları hazırlayın ve yerleştirin. Yalnızca PDF dosyaları ve maksimum 10MB boyutunda.",
        "Aşağıdaki QR kodunu tarayın ve sizi dosya yükleme portalına yönlendirecek olan bağlantıyı açın.",
        "Dosyaları portalda görüntülenen talimatları izleyerek mobil cihazınızdan yükleyin.",
        "Dosyaların alındığına dair onay e-postasını doğru aldığınızı kontrol edin ve e-postada gösterilen sipariş kimliğini aşağıdaki alana girin. 'Gönder' düğmesine basın.",
        "Bir dosya yüklemeyi unuttuysanız ve siparişe eklemek istiyorsanız, adım 2'den 4'e kadar tekrarlayın. Hazır olduğunuzda 'Bitir' düğmesine basın.",
        "Gönder",
        "Bitir",
        "E-posta adresi",
        "E-posta adresinizi girin",
        "Yüklenecek PDF dosyalarını seçin",
        "Sipariş numarası ve referans numarası ile size onay e-postası gönderebilmemiz için buna ihtiyacımız var.",
        "'Dosyaları seç' düğmesine basarak istediğiniz dosyaları seçin.",
        "Maksimum dosya boyutu: 10MB",
        "Devam et",
        "Neredeyse bitti...",
        "E-posta gelen kutunuzu kontrol edin, sipariş kimliğini içeren bir onay e-postası gönderdik. Yazdırma ayarlarına devam etmek için kimliği terminal kutusuna girmeniz gerekecek.",
        "Hiçbir şey almadıysanız, girdiğiniz e-posta adresinin yanlış olması muhtemeldir. Bu durumda, önceki ekrana dönün ve e-postayı tekrar girin. Ayrıca spam klasörünü kontrol edin."
    ],
    'ukrainian': [
        "Кроки",
        "Підготуйте та знайдіть файли на мобільному пристрої, який ви будете використовувати в цьому процесі. Тільки PDF-файли з максимальною розміром 10MB.",
        "Відскануйте наступний QR-код і відкрийте посилання, яке перенаправить вас на портал завантаження файлів.",
        "Завантажте файли з вашого мобільного пристрою, слідуючи інструкціям, які відображаються на порталі.",
        "Перевірте, чи правильно ви отримали електронний лист з підтвердженням отримання файлів, і введіть ідентифікатор замовлення, зазначений у листі, у наступне поле. Натисніть 'Надіслати'.",
        "Якщо ви забули завантажити файл і хочете додати його до замовлення, повторіть кроки 2 до 4. Натисніть 'Завершити', коли ви будете готові.",
        "Надіслати",
        "Завершити",
        "Адреса електронної пошти",
        "Введіть вашу електронну адресу",
        "Виберіть PDF-файли для завантаження",
        "Нам це потрібно, щоб надіслати вам лист підтвердження з номером замовлення та посиланням, щоб ви могли продовжити процес.",
        "Натисніть 'Вибрати файли', щоб вибрати бажані файли.",
        "Максимальний розмір файлу: 10MB",
        "Продовжити",
        "Ви майже готові...",
        "Перевірте вашу електронну пошту, ми надіслали вам лист підтвердження замовлення з ідентифікатором, який потрібно ввести в поле на терміналі, щоб продовжити налаштування друку.",
        "Якщо ви нічого не отримали, можливо, введена електронна адреса неправильна. У такому випадку поверніться на попередній екран і введіть електронну адресу знову. Перевірте також папку зі спамом."
    ],
    'welsh': [
        "Camau",
        "Paratowch a lleoli'r ffeiliau ar y ddyfais symudol y byddwch yn ei defnyddio yn y broses hon. Dim ond ffeiliau PDF a gyda maint uchaf o 10MB.",
        "Sganiwch y cod QR canlynol ac agorwch y ddolen a fydd yn eich ailgyfeirio i'r porth lanlwytho ffeiliau.",
        "Lanlwythwch y ffeiliau o'ch dyfais symudol gan ddilyn y cyfarwyddiadau a ddangosir ar y porth.",
        "Gwiriwch eich bod wedi derbyn yr e-bost cadarnhau derbyn ffeiliau'n gywir ac mewnosodwch yr adnabod archeb a ddangosir yn yr e-bost yn y maes canlynol. Pwyswch 'Anfon'.",
        "Os ydych wedi anghofio lanlwytho ffeil ac eisiau ei hychwanegu at yr archeb, ailadroddwch y camau 2 i 4. Pwyswch 'Gorffen' pan fyddwch yn barod.",
        "Anfon",
        "Gorffen",
        "Cyfeiriad e-bost",
        "Nodwch eich cyfeiriad e-bost",
        "Dewiswch y ffeiliau PDF i'w lanlwytho",
        "Mae arnom angen hyn i anfon yr e-bost cadarnhau atoch gyda rhif yr archeb a'r cyfeirnod fel y gallwch barhau gyda'r broses.",
        "Pwyswch 'Dewis ffeiliau' i ddewis y ffeiliau a ddymunir.",
        "Maint uchaf y ffeil: 10MB",
        "Parhau",
        "Rydych bron wedi gorffen...",
        "Gwiriwch eich blwch derbyn e-bost, rydym wedi anfon e-bost cadarnhau archeb atoch gyda'r adnabod y bydd angen i chi ei fewnosod yn y blwch terfynol i barhau gyda'r gosodiad argraffu.",
        "Os nad ydych wedi derbyn unrhyw beth, mae'n debygol nad yw'r cyfeiriad e-bost a nodwyd gennych yn gywir. Yn yr achos hwn, ewch yn ôl i'r sgrin flaenorol a nodwch yr e-bost eto. Gwiriwch hefyd eich ffolder sothach."
    ],
    'zh-CN': [
        "步骤",
        "准备并定位你将在此过程中使用的移动设备上的文件。仅限PDF文件，最大大小为10MB。",
        "扫描以下QR码并打开链接，该链接将重定向到文件上传门户。",
        "按照门户上显示的说明从移动设备上传文件。",
        "检查你是否已正确收到文件接收确认电子邮件，并在以下字段中输入电子邮件中显示的订单识别码。点击“发送”。",
        "如果你忘记上传某个文件并希望将其添加到订单中，请重复步骤2至4。准备就绪后点击“完成”。",
        "发送",
        "完成",
        "电子邮件地址",
        "输入你的电子邮件地址",
        "选择要上传的PDF文件",
        "我们需要它来向你发送带有订单号和参考号的确认电子邮件，以便你继续进行该过程。",
        "点击“选择文件”以选择所需的文件。",
        "文件最大大小：10MB",
        "继续",
        "你快完成了...",
        "检查你的电子邮件收件箱，我们已向你发送订单确认电子邮件，其中包含你需要输入到终端框中的识别码，以继续进行打印设置。",
        "如果你没有收到任何东西，可能是你输入的电子邮件地址不正确。在这种情况下，请返回上一屏幕并重新输入电子邮件。还请检查垃圾邮件文件夹。"
    ]
    }

    translations2 = {
    'arabic': [
        "معرّف طلبك هو التالي:",
        "خروج",
        "الخطوات",
        "موبايل",
        "بحث",
        "لم يتم اختيار أي ملف",
        "حذف",
        "ملفات مختارة",
        "ملف أو أكثر يتجاوز حد الحجم 10 ميجابايت. الرجاء إزالة هذه الملفات قبل المتابعة.",
        "لم يتم العثور على جلسة مع هذا المعرف. يرجى التحقق من أنك أدخلت الرمز بشكل صحيح.",
        "لم يتم اختيار أي ملف",
        "تنسيق أحد الملفات غير مناسب (.pdf)",
        "البريد الإلكتروني المقدم غير صالح"
    ],
    'basque': [
        "Zure eskaeraren IDa hau da:",
        "Irteera",
        "Pausoak",
        "Mugikorra",
        "Bilatu",
        "Ez da fitxategirik aukeratu",
        "Ezabatu",
        "hautatutako fitxategiak",
        "Fitxategi bat edo gehiago 10 MB-ko tamaina-muga gainditzen dute. Mesedez, ezabatu fitxategi hauek jarraitu aurretik.",
        "Ez da saio aktiborik aurkitu eskaera ID honekin. Mesedez, egiaztatu kodea ondo sartu duzun.",
        "Ez da fitxategirik aukeratu",
        "Fitxategi baten formatua ez da egokia (.pdf)",
        "Eman duzun helbide elektronikoa ez da baliozkoa"
    ],
    'catalan': [
        "L'ID de la teva comanda és el següent:",
        "Sortida",
        "Passos",
        "Mòbil",
        "Cerca",
        "No s'ha triat cap fitxer",
        "Eliminar",
        "fitxers seleccionats",
        "Un o més fitxers superen el límit de mida de 10 MB. Si us plau, elimina aquests fitxers abans de continuar.",
        "No hi ha cap sessió iniciada amb aquest ID de comanda. Revisa que hagis introduït bé el codi.",
        "No s'ha seleccionat cap fitxer",
        "El format d'un dels fitxers no és l'adequat (.pdf)",
        "L'adreça de correu proporcionada no correspon a un correu vàlid"
    ],
    'croatian': [
        "ID vaše narudžbe je sljedeći:",
        "Izlaz",
        "Koraci",
        "Mobilni",
        "Pretraži",
        "Nijedna datoteka nije odabrana",
        "Ukloni",
        "odabrani fajlovi",
        "Jedan ili više fajlova premašuju ograničenje veličine od 10 MB. Molimo uklonite te fajlove prije nastavka.",
        "Nema aktivne sesije s ovim ID-om narudžbe. Provjerite jeste li ispravno unijeli kod.",
        "Nijedna datoteka nije odabrana",
        "Format jednog od fajlova nije ispravan (.pdf)",
        "Navedena adresa e-pošte nije valjana"
    ],
    'danish': [
        "Dit bestillings-ID er følgende:",
        "Afslut",
        "Trin",
        "Mobil",
        "Søg",
        "Ingen filer valgt",
        "Fjern",
        "valgte filer",
        "En eller flere filer overstiger grænsen på 10 MB. Fjern venligst disse filer, før du fortsætter.",
        "Der er ingen aktiv session med dette bestillings-ID. Tjek venligst, at du har indtastet koden korrekt.",
        "Ingen filer valgt",
        "Formatet på en af filerne er ikke korrekt (.pdf)",
        "Den angivne e-mail-adresse er ikke gyldig"
    ],
    'dutch': [
        "Het ID van uw bestelling is als volgt:",
        "Uitgang",
        "Stappen",
        "Mobiel",
        "Zoeken",
        "Geen bestand geselecteerd",
        "Verwijderen",
        "geselecteerde bestanden",
        "Een of meer bestanden overschrijden de groottegrens van 10 MB. Verwijder deze bestanden voordat u doorgaat.",
        "Er is geen actieve sessie gevonden met dit bestel-ID. Controleer of u de code correct hebt ingevoerd.",
        "Geen bestand geselecteerd",
        "Het formaat van een van de bestanden is onjuist (.pdf)",
        "Het opgegeven e-mailadres is niet geldig"
    ],
    'english': [
        "Your order ID is the following:",
        "Exit",
        "Steps",
        "Mobile",
        "Search",
        "No file selected",
        "Remove",
        "selected files",
        "One or more files exceed the 10 MB size limit. Please remove these files before proceeding.",
        "There is no active session with this order ID. Please check that you have entered the code correctly.",
        "No file selected",
        "The format of one of the files is not correct (.pdf)",
        "The provided email address is not valid"
    ],
    'filipino': [
        "Ang ID ng iyong order ay ang mga sumusunod:",
        "Paglabas",
        "Mga Hakbang",
        "Mobile",
        "Maghanap",
        "Walang napiling file",
        "Alisin",
        "mga napiling file",
        "Isa o higit pang mga file ay lumampas sa limitasyong laki na 10 MB. Pakitanggal ang mga file na ito bago magpatuloy.",
        "Walang aktibong session na may ID ng order na ito. Mangyaring suriin na naipasok mo ang code nang tama.",
        "Walang napiling file",
        "Ang format ng isa sa mga file ay hindi tama (.pdf)",
        "Ang ibinigay na email address ay hindi wasto"
    ],
    'french': [
        "L'ID de votre commande est le suivant:",
        "Sortie",
        "Étapes",
        "Mobile",
        "Rechercher",
        "Aucun fichier sélectionné",
        "Supprimer",
        "fichiers sélectionnés",
        "Un ou plusieurs fichiers dépassent la limite de taille de 10 Mo. Veuillez supprimer ces fichiers avant de continuer.",
        "Aucune session active trouvée avec cet ID de commande. Veuillez vérifier que vous avez entré le code correctement.",
        "Aucun fichier sélectionné",
        "Le format de l'un des fichiers n'est pas correct (.pdf)",
        "L'adresse e-mail fournie n'est pas valide"
    ],
    'gd': [
        "Tha ID an òrduigh agad mar a leanas:",
        "Fàgail",
        "Ceumannan",
        "Làimhe",
        "Lorg",
        "Cha deach faidhle sam bith a thaghadh",
        "Sguab às",
        "faidhlichean air an taghadh",
        "Tha aon no barrachd fhaidhlichean nas motha na an crìoch 10 MB. Thoir air falbh iad mus lean thu air adhart.",
        "Chan eil seisean gnìomhach leis an ID òrduigh seo. Thoir sùil air an do chuir thu a-steach am bàrtha ceart.",
        "Cha deach faidhle sam bith a thaghadh",
        "Chan eil cruth aon de na faidhlichean ceart (.pdf)",
        "Chan eil an seòladh puist-d a thug thu seachad dligheach"
    ],
    'german': [
        "Ihre Bestell-ID lautet wie folgt:",
        "Ausgang",
        "Schritte",
        "Mobil",
        "Suchen",
        "Keine Datei ausgewählt",
        "Entfernen",
        "ausgewählte Dateien",
        "Eine oder mehrere Dateien überschreiten das Größenlimit von 10 MB. Bitte entfernen Sie diese Dateien, bevor Sie fortfahren.",
        "Es gibt keine aktive Sitzung mit dieser Bestell-ID. Bitte überprüfen Sie, ob Sie den Code richtig eingegeben haben.",
        "Keine Datei ausgewählt",
        "Das Format einer der Dateien ist nicht korrekt (.pdf)",
        "Die angegebene E-Mail-Adresse ist ungültig"
    ],
    'greek': [
        "Το αναγνωριστικό της παραγγελίας σας είναι το εξής:",
        "Έξοδος",
        "Βήματα",
        "Κινητό",
        "Αναζήτηση",
        "Δεν επιλέχθηκε κανένα αρχείο",
        "Αφαίρεση",
        "επιλεγμένα αρχεία",
        "Ένα ή περισσότερα αρχεία υπερβαίνουν το όριο μεγέθους των 10 MB. Αφαιρέστε αυτά τα αρχεία πριν συνεχίσετε.",
        "Δεν βρέθηκε ενεργή συνεδρία με αυτό το αναγνωριστικό παραγγελίας. Ελέγξτε ότι έχετε εισάγει σωστά τον κωδικό.",
        "Δεν επιλέχθηκε κανένα αρχείο",
        "Η μορφή ενός από τα αρχεία δεν είναι σωστή (.pdf)",
        "Η παρεχόμενη διεύθυνση email δεν είναι έγκυρη"
    ],
    'italian': [
        "L'ID del tuo ordine è il seguente:",
        "Uscita",
        "Passaggi",
        "Mobile",
        "Cerca",
        "Nessun file selezionato",
        "Rimuovi",
        "file selezionati",
        "Uno o più file superano il limite di dimensione di 10 MB. Si prega di rimuovere questi file prima di procedere.",
        "Non esiste alcuna sessione attiva con questo ID ordine. Controlla di aver inserito correttamente il codice.",
        "Nessun file selezionato",
        "Il formato di uno dei file non è corretto (.pdf)",
        "L'indirizzo email fornito non è valido"
    ],
    'japanese': [
        "あなたの注文IDは次のとおりです：",
        "出口",
        "ステップ",
        "モバイル",
        "検索",
        "ファイルが選択されていません",
        "削除",
        "選択されたファイル",
        "1つ以上のファイルが10 MBのサイズ制限を超えています。これらのファイルを削除してから続行してください。",
        "この注文IDでアクティブなセッションはありません。コードが正しく入力されていることを確認してください。",
        "ファイルが選択されていません",
        "ファイルの1つの形式が適切ではありません（.pdf）",
        "提供されたメールアドレスが有効ではありません"
    ],
    'norwegian': [
        "Din bestillings-ID er følgende:",
        "Avslutt",
        "Trinn",
        "Mobil",
        "Søk",
        "Ingen fil valgt",
        "Fjern",
        "valgte filer",
        "En eller flere filer overskrider størrelsesgrensen på 10 MB. Vennligst fjern disse filene før du fortsetter.",
        "Det er ingen aktiv sesjon med denne bestillings-IDen. Vennligst sjekk at du har angitt koden riktig.",
        "Ingen fil valgt",
        "Formatet på en av filene er ikke riktig (.pdf)",
        "Den oppgitte e-postadressen er ikke gyldig"
    ],
    'polish': [
        "ID twojego zamówienia to:",
        "Wyjście",
        "Kroki",
        "Mobilny",
        "Szukaj",
        "Nie wybrano pliku",
        "Usuń",
        "wybrane pliki",
        "Jeden lub więcej plików przekracza limit rozmiaru 10 MB. Przed kontynuowaniem usuń te pliki.",
        "Nie znaleziono aktywnej sesji z tym ID zamówienia. Sprawdź, czy poprawnie wprowadziłeś kod.",
        "Nie wybrano pliku",
        "Format jednego z plików jest nieprawidłowy (.pdf)",
        "Podany adres e-mail jest nieprawidłowy"
    ],
    'portuguese': [
        "O ID do seu pedido é o seguinte:",
        "Saída",
        "Passos",
        "Móvel",
        "Procurar",
        "Nenhum arquivo selecionado",
        "Remover",
        "arquivos selecionados",
        "Um ou mais arquivos excedem o limite de tamanho de 10 MB. Por favor, remova esses arquivos antes de prosseguir.",
        "Não há sessão ativa com este ID de pedido. Verifique se você inseriu o código corretamente.",
        "Nenhum arquivo selecionado",
        "O formato de um dos arquivos não é correto (.pdf)",
        "O endereço de e-mail fornecido não é válido"
    ],
    'serbian': [
        "ID vaše narudžbine je sledeći:",
        "Izlaz",
        "Koraci",
        "Mobilni",
        "Pretraži",
        "Nijedan fajl nije izabran",
        "Ukloni",
        "odabrani fajlovi",
        "Jedan ili više fajlova premašuje ograničenje veličine od 10 MB. Molimo uklonite te fajlove pre nego što nastavite.",
        "Ne postoji aktivna sesija sa ovim ID-om narudžbine. Proverite da li ste pravilno uneli kod.",
        "Nijedan fajl nije izabran",
        "Format jednog od fajlova nije odgovarajući (.pdf)",
        "Uneta adresa e-pošte nije važeća"
    ],
    'spanish': [
        "El ID de tu pedido es el siguiente:",
        "Salida",
        "Pasos",
        "Móvil",
        "Buscar",
        "No se ha seleccionado ningún archivo",
        "Eliminar",
        "archivos seleccionados",
        "Uno o más archivos superan el límite de tamaño de 10 MB. Por favor, elimina estos archivos antes de continuar.",
        "No hay ninguna sesión activa con este ID de pedido. Revisa que hayas introducido correctamente el código.",
        "No se ha seleccionado ningún archivo",
        "El formato de uno de los archivos no es adecuado (.pdf)",
        "La dirección de correo proporcionada no es válida"
    ],
    'swedish': [
        "Ditt beställnings-ID är följande:",
        "Avsluta",
        "Steg",
        "Mobil",
        "Sök",
        "Ingen fil vald",
        "Ta bort",
        "valda filer",
        "En eller flera filer överskrider storleksgränsen på 10 MB. Ta bort dessa filer innan du fortsätter.",
        "Det finns ingen aktiv session med detta beställnings-ID. Kontrollera att du har angett koden korrekt.",
        "Ingen fil vald",
        "Formatet på en av filerna är inte korrekt (.pdf)",
        "Den angivna e-postadressen är inte giltig"
    ],
    'turkish': [
        "Sipariş kimliğiniz aşağıdaki gibidir:",
        "Çıkış",
        "Adımlar",
        "Mobil",
        "Ara",
        "Dosya seçilmedi",
        "Kaldır",
        "seçilen dosyalar",
        "Bir veya daha fazla dosya 10 MB boyut sınırını aşıyor. Lütfen devam etmeden önce bu dosyaları kaldırın.",
        "Bu sipariş kimliği ile ilgili aktif bir oturum bulunamadı. Kodu doğru girdiğinizden emin olun.",
        "Dosya seçilmedi",
        "Dosyalardan birinin formatı uygun değil (.pdf)",
        "Verilen e-posta adresi geçerli değil"
    ],
    'ukrainian': [
        "Ідентифікатор вашого замовлення наступний:",
        "Вихід",
        "Кроки",
        "Мобільний",
        "Пошук",
        "Файл не вибрано",
        "Видалити",
        "вибрані файли",
        "Один або більше файлів перевищують обмеження розміру 10 МБ. Видаліть ці файли перед тим, як продовжити.",
        "Не знайдено активної сесії з цим ідентифікатором замовлення. Перевірте правильність введення коду.",
        "Файл не вибрано",
        "Формат одного з файлів не підходить (.pdf)",
        "Надана адреса електронної пошти є недійсною"
    ],
    'welsh': [
        "ID eich archeb yw'r canlynol:",
        "Allanfa",
        "Camau",
        "Symudol",
        "Chwilio",
        "Dim ffeil wedi'i ddewis",
        "Dileu",
        "ffeiliau a ddewiswyd",
        "Mae un neu fwy o ffeiliau'n fwy na'r terfyn maint o 10 MB. Dileu'r ffeiliau hyn cyn parhau.",
        "Nid oes unrhyw sesiwn weithredol gyda'r ID archeb hwn. Gwiriwch eich bod wedi rhoi'r cod yn iawn.",
        "Dim ffeil wedi'i ddewis",
        "Nid yw'r fformat o un o'r ffeiliau'n gywir (.pdf)",
        "Nid yw'r cyfeiriad e-bost a roddwyd yn ddilys"
    ],
    'zh-CN': [
        "您的订单编号如下：",
        "出口",
        "步骤",
        "手机",
        "搜索",
        "未选择文件",
        "删除",
        "已选择的文件",
        "一个或多个文件超过10 MB大小限制。请删除这些文件后再继续。",
        "未找到与此订单编号关联的活动会话。请检查您是否正确输入了代码。",
        "未选择文件",
        "其中一个文件的格式不正确（.pdf）",
        "提供的电子邮件地址无效"
    ]
}


    if fun == 1:
        return translations[lang][:8]
    elif fun == 2:
        return translations[lang][8:15]
    elif fun == 3:
        return translations[lang][15:]
    elif fun == 4:
        return [translations2[lang][1]]
    elif fun == 5:
        return [translations2[lang][0],translations2[lang][3],translations2[lang][4],translations2[lang][5],translations2[lang][6],translations2[lang][7],translations2[lang][11],translations2[lang][12]]
    elif fun == 6:
        return [translations2[lang][2],translations2[lang][9]]
        

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def allowed_mail(mail):
    # Simple Regex for syntax checking
    regex = '^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,})$'
    addressToVerify = str(mail)

    # Syntax check
    match = re.match(regex, addressToVerify)
    if match == None:
        print('Bad Syntax')
        raise ValueError('Bad Syntax')
    
    #Deliverability check

    try:

        # Check that the email address is valid. Turn on check_deliverability
        # for first-time validations like on account creation pages (but not
        # login pages).
        emailinfo = validate_email(addressToVerify, check_deliverability=True)
        return True

    except EmailNotValidError as e:
        # The exception message is human-readable explanation of why it's
        # not a valid (or deliverable) email address.
        print(str(e))
        return False



def send_mail(text,id,recipient):

    sender_email = "noreply.verdi9@gmail.com"
    sender_password = PASSWORD
    recipient_email = recipient
    subject = "No-reply session ID"
    body = render_template("mail.html",id=id,text=text)
    html_message = MIMEText(body, 'html')
    html_message['Subject'] = subject
    html_message['From'] = sender_email
    html_message['To'] = recipient_email
    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
        server.login(sender_email, sender_password)
        server.sendmail(sender_email, recipient_email, html_message.as_string())
